name: animated_counter_x
description: "A Flutter widget that animates numbers (integers or doubles) from a start value to an end value with customizable duration and direction (increment or decrement)."
version: 0.0.1
homepage: https://github.com/abqamar/animated_counter_x.git
repository: https://github.com/abqamar/animated_counter_x.git

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
